### ISSUE TITLE
Requesting release of pg generation script with instructions.

### ISSUE THREAD

**Issue by touranisatyajit** [thusiyuan/holistic_scene_parsing#4]
Hi,

Thank you for releasing the inference code.

The preprocessed images contain their respective pg files. Could you please release the script and instructions on how to do that for custom dataset images? 

Thanks.

**Comment by thusiyuan** [comment]
Hi,

Thank you for pointing out the request.

We may release the preprocessing code which generates the pgs in next month.

**Comment by evandesantola** [comment]
I wanted to follow up on the above.  Do you guys have any updates on this?
